version: '3'
services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: '2.6.3'
        BUNDLER_VERSION: '2.0.2'
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .:/usr/src/app
      - app_assets:/usr/local/src/app/public/assets/
      - app_file_storage:/app/public/system/
      - app_tmp_cache:/usr/local/src/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    links:
      - pg
    command: bundle exec puma
    depends_on:
      - pg
  pg:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
  worker:
    build:
      context: .
      args:
        RUBY_VERSION: '2.6.3'
        BUNDLER_VERSION: '2.0.2'
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    links:
      - pg
    command: bundle exec rails jobs:work
    depends_on:
      - pg


volumes:
  app_assets: {}
  app_file_storage: {}
  app_tmp_cache: {}
  bundle: {}
  node_modules: {}
  pg-data: {}
